### ISSUE TITLE
LAG (LACP) member status on remote port down.

### ISSUE THREAD

**Issue by vnam1** [open-switch/opx-nas-l2#20]
I have LAG in LACP mode. Is there a way to find out if a member port is down? 
Looking for a command similar to what cumulus provides to get LAG member status: "netshow bondmems"
Status information is not available in /proc/net/bonding/bond<x>
Also in my setup switch and the server are not directly connected but over a QinQ tunnel.
So, can not get this info from physical layer.

**Comment by jeff-yin** [comment]
@nchervela I believe you had come to a closure on this issue in a separate conversation with @vnam1. Can you provide the resolution here and close the issue? Thanks

**Comment by nchervela** [comment]
Issue resolved on rocket chat (please see below). OPX 3.0.0 will have detailed information on actor and partner churn states, as requested.



nchervela 11:27 AM   
@vnam1 This is indeed an issue with linux distro/version. The next release of OPX (3.0.0) will have the missing info. Pls see below the output with OPX 3.0.0-dev1 -
root@OPX:~# cat /proc/net/bonding/bond1
Ethernet Channel Bonding Driver: v3.7.1 (April 27, 2011)

Bonding Mode: IEEE 802.3ad Dynamic link aggregation
Transmit Hash Policy: layer2 (0)
MII Status: up
MII Polling Interval (ms): 100
Up Delay (ms): 0
Down Delay (ms): 0

802.3ad info
LACP rate: slow
Min links: 0
Aggregator selection policy (ad_select): stable
System priority: 65535
System MAC address: 90:b1:1c:f4:b3:e2
Active Aggregator Info:
Aggregator ID: 1
Number of ports: 2
Actor Key: 5
Partner Key: 5
Partner Mac Address: 90:b1:1c:f4:9d:22

Slave Interface: e101-001-0
MII Status: up
Speed: 10 Mbps
Duplex: full
Link Failure Count: 2
Permanent HW addr: 90:b1:1c:f4:b3:7a
Slave queue ID: 0
Aggregator ID: 1
Actor Churn State: monitoring
Partner Churn State: monitoring
Actor Churned Count: 0
Partner Churned Count: 0
details actor lacp pdu:
system priority: 65535
system mac address: 90:b1:1c:f4:b3:e2
port key: 5
port priority: 255
port number: 1
port state: 61
details partner lacp pdu:
system priority: 65535
system mac address: 90:b1:1c:f4:9d:22
oper key: 5
port priority: 255
port number: 1
port state: 61

Slave Interface: e101-002-0
MII Status: up
Speed: 10 Mbps
Duplex: full
Link Failure Count: 1
Permanent HW addr: 90:b1:1c:f4:b3:7e
Slave queue ID: 0
Aggregator ID: 1
Actor Churn State: none
Partner Churn State: none
Actor Churned Count: 0
Partner Churned Count: 0
details actor lacp pdu:
system priority: 65535
system mac address: 90:b1:1c:f4:b3:e2
port key: 5
port priority: 255
port number: 2
port state: 61
details partner lacp pdu:
system priority: 65535
system mac address: 90:b1:1c:f4:9d:22
oper key: 5
port priority: 255
port number: 2
port state: 61

e101-027-1.100
root@OPX:~# ip link show e101-001-0
11: e101-001-0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond1 state UP mode DEFAULT group default qlen 1000
link/ether 90:b1:1c:f4:b3:e2 brd ff:ff:ff:ff:ff:ff
alias NAS## 0 25
root@OPX:~# ip link show e101-002-0
12: e101-002-0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond1 state UP mode DEFAULT group default qlen 1000
link/ether 90:b1:1c:f4:b3:e2 brd ff:ff:ff:ff:ff:ff
alias NAS## 0 29
  
@vnam1 The installer for OPX 3.0.0-dev1 has been published to http://archive.openswitch.net. This is the alpha release of what will become OPX 3.0.0. It is the first release that is based on Debian Stretch (previous versions of OPX were based on Debian Jessie). 
Note that we have not yet performed extensive functional and system testing on this release. Thus far, the effort has been to get a successful Stretch-based build where systems boot up with all services running.

vnam1 2:11 PM
Thanks @nchervela . When is OPX 3.0.0 expected release?

vnam1 2:18 PM
With 2.3.0 VM we are seeing traffic issue with L2 config. Please see https://github.com/open-switch/opx-nas-l2/issues/21 for details.
 
github.com
Traffic drop on OPX VM · Issue #21 · open-switch/opx-nas-l2
I have an OPX VM that has a bridge configured ‘br10’ br10 Link encap:Ethernet HWaddr 52:54:00:13:99:28 inet addr:172.16.2.1 Bcast:0.0.0.0 Mask:255.255.255.0 inet6 addr: fe80::5054:ff:fe13:9928/64 S...

jyin Owner 9:37 AM
OPX 3.0.0 expected release is early August

vnam1 10:45 AM
Thanks @jyin

**Comment by nchervela** [comment]
Jeff,
I updated the issue, but I don't see a “close” button anywhere.
Thanks,
Nalini
