### ISSUE TITLE
Recommended to turn off STP.

### ISSUE THREAD

**Issue by vnam1** [open-switch/opx-nas-l2#22]
It was recommended to turn STP off.
Need to fix to remove this restriction.

**Comment by jeff-yin** [comment]
It was recommended to turn off STP on host-facing access ports, since there will not be any L2 loops on those kinds of ports. Not sure if Linux STP has any way to configure something like "portfast".

Need more info about this request. Is it causing some behavioral issue or restriction?

**Comment by vnam1** [comment]
Right now there is no issue but once we support MLAG this may cause issues.

**Comment by jeff-yin** [comment]
Closing due to non-response for more info. Feel free to reopen when you're able to provide more info.
